name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Node 12.18.2
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.2

      - name: npm install and npm run build
        run: |
          npm ci
          npm run build:ci
