name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm install and npm run build
        run: |
          npm i
          npm build
        
